greeting:
 message: Hello there how are you.
numbers:
 list: one,two,three
app:
 name: Developement App
 description: Welcome to ${app.name}


db:
 connection: Dev-connection-String from application.
 port: 1200
 host: 127.0.0

server.port: 8084

management.endpoints.web.exposure.include: "*"

spring:
 application:
  name: spring-boot-config
